### ISSUE TITLE
make repo public

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/docker-receval#1]

**Comment by physikerwelt** [comment]
blocks #2

**Comment by malteos** [comment]
Actually, the repo can remain private. I just need to manually push to docker hub: https://hub.docker.com/repository/docker/malteos/receval

**Comment by malteos** [comment]
Otherwise, I need to remove the dummy data, because it includes zbMath documens: https://github.com/ag-gipp/docker-receval/blob/master/receval/apps/explorer/fixtures/dummy.json

**Comment by physikerwelt** [comment]
I think it would be good if the repo is public. Manually pushing to Docker would not help as the data is still public in that case. And it is harder to debug and reproduce.

**Comment by malteos** [comment]
Repo is public.
